"""Assert byte-identical generated research and production outputs using the offline snapshot."""
import subprocess, sys
from build_worlds_2017 import ROOT, OUT, sha, write

files=[ROOT/'src/data/worlds-2017.json']+[OUT/f for f in ['evidence.json','rosters.json','player-stats.json',
       'player-champion-stats.json','normalization.json','sources.json','coverage.json','matches.json']]
before={p.relative_to(ROOT).as_posix():sha(p) for p in files}
subprocess.run([sys.executable, str(ROOT/'scripts/data/build_worlds_2017.py'),'--snapshot'],check=True,cwd=ROOT)
after={p.relative_to(ROOT).as_posix():sha(p) for p in files}
assert before==after, 'Offline regeneration changed generated bytes.'
write(OUT/'reproducibility.json',dict(mode='frozen snapshot versus full CSV outputs',passed=True,sha256=after))
print(f'{len(files)} files reproduced byte-for-byte.')
