import type { PlayerVersion } from '../game/types';
import researched from './multi-era.json';

// Generated by scripts/data/build_multi_era.py. Provenance: data/research/multi-era/evidence-{year}.json.
export const players: PlayerVersion[] = researched as PlayerVersion[];
